(() => {
  const locales = ['de', 'en', 'es', 'fr', 'ja', 'ko', 'nl', 'zh-CN', 'zh-TW'];
  const labels = { de:'Deutsch', en:'English', es:'Español', fr:'Français', ja:'日本語', ko:'한국어', nl:'Nederlands', 'zh-CN':'简体中文', 'zh-TW':'繁體中文' };
  const source = {
    map:'地图', journeys:'旅程', privacy:'隐私', privacyPolicy:'隐私政策', download:'下载', designed:'为 iPhone 与 iPad 设计',
    hero1:'把照片放回', hero2:'它们发生的地方', lede:'在地图上探索照片足迹，重拾每一段旅程，并把走过的地方变成属于你的旅行故事。',
    explore:'看看它能做什么', local:'无需创建账户 · 照片留在你的设备上', photos:'224 张照片', spring:'一个春天', trail:'沿着足迹继续',
    geography:'你的照片地理', mapTitle:'相册，也是一张\n只属于你的旅行地图。', mapCopy:'从城市里的一个街角，到跨越数年的足迹。缩放、搜索、按时间浏览，在熟悉的地图上重新遇见那些照片。',
    photoMap:'照片地图 · Amsterdam', memories:'224 个回忆', placeSearch:'地点搜索', placeSearchCopy:'回到记忆中的街道', timeFilter:'时间筛选', timeFilterCopy:'按年月与季节浏览', mapStyle:'地图样式', mapStyleCopy:'标准、卫星与热力图',
    toStories:'从足迹，到故事', beyond:'不只是地图。', storiesCopy:'把分散的照片，整理成可以重温、理解，也可以分享的旅程。', journey:'旅程', journeyTitle:'把一段路，收进一张卡片', journeyCopy:'日期、地点与照片自然串成旅程。', poster:'旅行海报', posterTitle:'让回忆成为一张海报', posterCopy:'地图、路线和照片排成你的旅行纪念。', stats:'旅行统计', cities:'城市', statsTitle:'看见走过的距离', statsCopy:'用清晰的数据回望一年的探索。', locationTools:'位置工具', dragMap:'拖动地图，找回地点', locationTitle:'为照片补回坐标', locationCopy:'添加或修复位置，让每张照片都能归位。', photoFilter:'照片筛选', springShort:'春天', weekend:'周末', filterTitle:'从千张照片里找到这一刻', filterCopy:'按时间、季节和地点快速缩小范围。', browse:'横向浏览',
    premium:'PhotoLoci 高级功能', premiumTitle:'一次解锁，\n所有高级工具。', premiumCopy:'旅程、旅行海报、统计、添加位置与位置修复；另含照片筛选和地点搜索。没有订阅，也没有倒计时。', premiumButton:'在 App 内查看高级功能', regionalPrice:'价格会在 App Store 中按你所在地区显示', advanced:'高级工具', lifetime:'一次解锁 · 终身使用',
    yours:'照片属于你', privateTitle:'回忆很私人。\n处理也应如此。', onDevice:'在设备上处理', onDeviceCopy:'照片分析与地图聚合在你的设备上完成。', permissions:'由你决定权限', permissionsCopy:'照片与位置访问随时可以在系统设置中更改。', readPrivacy:'阅读隐私政策', next:'下一站，从相册开始', rediscover:'重新发现\n走过的地方。', finalCopy:'让每一张照片，都在地图上找到自己的位置。', footerCopy:'把照片放回它们发生的地方。', contact:'联系我们', language:'语言'
  };
  const messages = {
    en:{map:'Map',journeys:'Journeys',privacy:'Privacy',download:'Download',designed:'Designed for iPhone and iPad',hero1:'Put your photos back',hero2:'where they happened',lede:'Explore your photo trail on a map, rediscover every journey, and turn the places you have been into your own travel stories.',explore:'See what it can do',local:'No account needed · Your photos stay on your device',photos:'224 photos',spring:'One spring',trail:'Follow the trail',geography:'Your photo geography',mapTitle:'Your library is a travel map\nthat belongs only to you.',mapCopy:'From a street corner to years of travel. Zoom, search, and browse by time to meet your photos again on a familiar map.',photoMap:'Photo map · Amsterdam',memories:'224 memories',placeSearch:'Place search',placeSearchCopy:'Return to a remembered street',timeFilter:'Time filters',timeFilterCopy:'Browse by year, month, or season',mapStyle:'Map styles',mapStyleCopy:'Standard, satellite, and heatmap',toStories:'From trails to stories',beyond:'More than a map.',storiesCopy:'Turn scattered photos into journeys you can revisit, understand, and share.',journey:'Journey',journeyTitle:'Keep a route in one card',journeyCopy:'Dates, places, and photos flow into a journey.',poster:'Travel poster',posterTitle:'Turn a memory into a poster',posterCopy:'Maps, routes, and photos become a travel keepsake.',stats:'Travel stats',cities:'cities',statsTitle:'See how far you have gone',statsCopy:'Look back on a year of exploring through clear data.',locationTools:'Location tools',dragMap:'Drag the map to recover a place',locationTitle:'Restore coordinates to photos',locationCopy:'Add or repair locations so every photo finds its place.',photoFilter:'Photo filters',springShort:'Spring',weekend:'Weekend',filterTitle:'Find this moment among thousands',filterCopy:'Quickly narrow photos by time, season, and place.',browse:'Browse horizontally',premium:'PhotoLoci Premium',premiumTitle:'Unlock once.\nGet every premium tool.',premiumCopy:'Journeys, travel posters, stats, adding and repairing locations, plus photo filters and place search. No subscription and no countdown.',premiumButton:'View Premium in the app',regionalPrice:'Pricing is shown in the App Store for your region',advanced:'Premium tools',lifetime:'Unlock once · Use forever',yours:'Your photos are yours',privateTitle:'Memories are private.\nTheir processing should be too.',onDevice:'Processed on device',onDeviceCopy:'Photo analysis and map aggregation happen on your device.',permissions:'You control access',permissionsCopy:'Change photo and location access anytime in system settings.',readPrivacy:'Read the privacy policy',next:'Your next stop starts in Photos',rediscover:'Rediscover the places\nyou have been.',finalCopy:'Let every photo find its place on the map.',footerCopy:'Put photos back where they happened.',contact:'Contact',language:'Language'},
    de:{map:'Karte',journeys:'Reisen',privacy:'Datenschutz',download:'Laden',designed:'Für iPhone und iPad entwickelt',hero1:'Bring deine Fotos zurück',hero2:'an den Ort des Moments',lede:'Entdecke deine Fotospuren auf der Karte, erlebe jede Reise neu und verwandle besuchte Orte in deine eigenen Geschichten.',explore:'Funktionen entdecken',local:'Kein Konto nötig · Fotos bleiben auf deinem Gerät',photos:'224 Fotos',spring:'Ein Frühling',trail:'Der Spur folgen',geography:'Deine Fotogeografie',mapTitle:'Deine Mediathek ist eine Reisekarte,\ndie nur dir gehört.',mapCopy:'Von einer Straßenecke bis zu Jahren voller Reisen. Zoome, suche und stöbere nach Zeit, um deinen Fotos wieder zu begegnen.',photoMap:'Fotokarte · Amsterdam',memories:'224 Erinnerungen',placeSearch:'Ortssuche',placeSearchCopy:'Zur Straße deiner Erinnerung',timeFilter:'Zeitfilter',timeFilterCopy:'Nach Jahr, Monat oder Saison',mapStyle:'Kartenstile',mapStyleCopy:'Standard, Satellit und Heatmap',toStories:'Von Spuren zu Geschichten',beyond:'Mehr als eine Karte.',storiesCopy:'Mach aus verstreuten Fotos Reisen, die du neu erleben, verstehen und teilen kannst.',journey:'Reise',journeyTitle:'Eine Route in einer Karte',journeyCopy:'Daten, Orte und Fotos werden ganz natürlich zur Reise.',poster:'Reiseposter',posterTitle:'Erinnerungen als Poster',posterCopy:'Karten, Routen und Fotos werden zum Reiseandenken.',stats:'Reisestatistik',cities:'Städte',statsTitle:'Sieh, wie weit du gekommen bist',statsCopy:'Blicke mit klaren Daten auf ein Jahr voller Entdeckungen zurück.',locationTools:'Ortungswerkzeuge',dragMap:'Karte ziehen und Ort wiederfinden',locationTitle:'Koordinaten ergänzen',locationCopy:'Orte hinzufügen oder korrigieren, damit jedes Foto seinen Platz findet.',photoFilter:'Fotofilter',springShort:'Frühling',weekend:'Wochenende',filterTitle:'Diesen Moment wiederfinden',filterCopy:'Fotos schnell nach Zeit, Saison und Ort eingrenzen.',browse:'Horizontal scrollen',premium:'PhotoLoci Premium',premiumTitle:'Einmal freischalten.\nAlle Premium-Werkzeuge.',premiumButton:'Premium in der App ansehen',advanced:'Premium-Werkzeuge',lifetime:'Einmal freischalten · Für immer nutzen',yours:'Deine Fotos gehören dir',privateTitle:'Erinnerungen sind privat.\nIhre Verarbeitung auch.',onDevice:'Auf dem Gerät verarbeitet',permissions:'Du bestimmst den Zugriff',readPrivacy:'Datenschutzrichtlinie lesen',next:'Der nächste Halt beginnt in Fotos',rediscover:'Entdecke besuchte\nOrte neu.',finalCopy:'Lass jedes Foto seinen Platz auf der Karte finden.',footerCopy:'Fotos zurück an den Ort ihres Moments.',contact:'Kontakt',language:'Sprache'},
    es:{map:'Mapa',journeys:'Viajes',privacy:'Privacidad',download:'Descargar',designed:'Diseñado para iPhone y iPad',hero1:'Devuelve tus fotos',hero2:'al lugar donde ocurrieron',lede:'Explora el rastro de tus fotos en el mapa, revive cada viaje y convierte los lugares visitados en tus propias historias.',explore:'Descubre lo que hace',local:'Sin cuenta · Tus fotos permanecen en tu dispositivo',photos:'224 fotos',spring:'Una primavera',trail:'Sigue el rastro',geography:'Tu geografía fotográfica',mapTitle:'Tu fototeca también es un mapa\nde viajes solo tuyo.',mapCopy:'Desde una esquina hasta años de viajes. Amplía, busca y explora por fecha para reencontrarte con tus fotos.',photoMap:'Mapa de fotos · Ámsterdam',memories:'224 recuerdos',placeSearch:'Buscar lugares',placeSearchCopy:'Vuelve a una calle recordada',timeFilter:'Filtros de tiempo',timeFilterCopy:'Explora por año, mes o estación',mapStyle:'Estilos de mapa',mapStyleCopy:'Estándar, satélite y mapa de calor',toStories:'De huellas a historias',beyond:'Más que un mapa.',storiesCopy:'Convierte fotos dispersas en viajes que puedas revivir, comprender y compartir.',journey:'Viaje',journeyTitle:'Guarda una ruta en una tarjeta',journeyCopy:'Fechas, lugares y fotos forman un viaje.',poster:'Póster de viaje',posterTitle:'Convierte recuerdos en pósteres',posterCopy:'Mapas, rutas y fotos crean un recuerdo de viaje.',stats:'Estadísticas',cities:'ciudades',statsTitle:'Mira cuánto has recorrido',statsCopy:'Repasa un año de exploración con datos claros.',locationTools:'Herramientas de ubicación',dragMap:'Arrastra el mapa para recuperar el lugar',locationTitle:'Recupera las coordenadas',locationCopy:'Añade o corrige ubicaciones para que cada foto encuentre su sitio.',photoFilter:'Filtros de fotos',springShort:'Primavera',weekend:'Fin de semana',filterTitle:'Encuentra este instante entre miles',filterCopy:'Filtra rápidamente por fecha, estación y lugar.',browse:'Explorar horizontalmente',premium:'PhotoLoci Premium',premiumTitle:'Desbloquea una vez.\nObtén todas las herramientas.',premiumButton:'Ver Premium en la app',advanced:'Herramientas premium',lifetime:'Un pago · Para siempre',yours:'Tus fotos son tuyas',privateTitle:'Los recuerdos son privados.\nSu tratamiento también.',onDevice:'Procesado en el dispositivo',permissions:'Tú controlas el acceso',readPrivacy:'Leer la política de privacidad',next:'La próxima parada empieza en Fotos',rediscover:'Redescubre los lugares\nque has visitado.',finalCopy:'Deja que cada foto encuentre su lugar en el mapa.',footerCopy:'Devuelve las fotos al lugar donde ocurrieron.',contact:'Contacto',language:'Idioma'},
    fr:{map:'Carte',journeys:'Voyages',privacy:'Confidentialité',download:'Télécharger',designed:'Conçu pour iPhone et iPad',hero1:'Replacez vos photos',hero2:'là où elles ont été prises',lede:'Explorez vos traces photographiques sur une carte, revivez chaque voyage et transformez les lieux parcourus en récits.',explore:'Découvrir les fonctions',local:'Aucun compte · Vos photos restent sur votre appareil',photos:'224 photos',spring:'Un printemps',trail:'Suivre les traces',geography:'Votre géographie photo',mapTitle:'Votre photothèque est aussi une carte\nde voyage rien qu’à vous.',mapCopy:'Du coin d’une rue à des années de voyages. Zoomez, recherchez et parcourez le temps pour retrouver vos photos.',photoMap:'Carte photo · Amsterdam',memories:'224 souvenirs',placeSearch:'Recherche de lieux',placeSearchCopy:'Retrouvez une rue familière',timeFilter:'Filtres temporels',timeFilterCopy:'Par année, mois ou saison',mapStyle:'Styles de carte',mapStyleCopy:'Standard, satellite et thermique',toStories:'Des traces aux récits',beyond:'Plus qu’une carte.',storiesCopy:'Transformez des photos dispersées en voyages à revivre, comprendre et partager.',journey:'Voyage',journeyTitle:'Un itinéraire dans une carte',journeyCopy:'Dates, lieux et photos composent naturellement un voyage.',poster:'Affiche de voyage',posterTitle:'Transformez un souvenir en affiche',posterCopy:'Cartes, trajets et photos deviennent un souvenir de voyage.',stats:'Statistiques',cities:'villes',statsTitle:'Voyez le chemin parcouru',statsCopy:'Revisitez une année d’exploration avec des données claires.',locationTools:'Outils de localisation',dragMap:'Faites glisser la carte pour retrouver le lieu',locationTitle:'Restaurez les coordonnées',locationCopy:'Ajoutez ou corrigez des lieux pour que chaque photo trouve sa place.',photoFilter:'Filtres photo',springShort:'Printemps',weekend:'Week-end',filterTitle:'Retrouvez cet instant parmi des milliers',filterCopy:'Affinez rapidement par date, saison et lieu.',browse:'Parcourir horizontalement',premium:'PhotoLoci Premium',premiumTitle:'Débloquez une fois.\nProfitez de tous les outils.',premiumButton:'Voir Premium dans l’app',advanced:'Outils premium',lifetime:'Un achat · Pour toujours',yours:'Vos photos vous appartiennent',privateTitle:'Les souvenirs sont privés.\nLeur traitement aussi.',onDevice:'Traité sur l’appareil',permissions:'Vous contrôlez les accès',readPrivacy:'Lire la politique de confidentialité',next:'La prochaine étape commence dans Photos',rediscover:'Redécouvrez les lieux\nque vous avez parcourus.',finalCopy:'Que chaque photo retrouve sa place sur la carte.',footerCopy:'Replacez les photos là où elles ont été prises.',contact:'Contact',language:'Langue'},
    ja:{map:'マップ',journeys:'旅',privacy:'プライバシー',download:'ダウンロード',designed:'iPhoneとiPadのために設計',hero1:'写真を、あの日の',hero2:'場所へ戻そう',lede:'写真の足跡を地図でたどり、旅をもう一度。訪れた場所を、あなただけの物語に変えます。',explore:'できることを見る',local:'アカウント不要 · 写真はデバイス内に保存',photos:'224枚の写真',spring:'ある春の日',trail:'足跡をたどる',geography:'あなたの写真地理',mapTitle:'フォトライブラリは、\nあなただけの旅の地図。',mapCopy:'街角から何年にもわたる旅まで。拡大、検索、時系列で閲覧し、地図の上で写真と再会できます。',photoMap:'写真マップ · アムステルダム',memories:'224の思い出',placeSearch:'場所を検索',placeSearchCopy:'思い出の通りへ戻る',timeFilter:'時間フィルター',timeFilterCopy:'年・月・季節で見る',mapStyle:'マップスタイル',mapStyleCopy:'標準・衛星・ヒートマップ',toStories:'足跡から物語へ',beyond:'地図だけではありません。',storiesCopy:'点在する写真を、振り返り、理解し、共有できる旅にまとめます。',journey:'旅',journeyTitle:'ひとつのルートを一枚のカードに',journeyCopy:'日付、場所、写真が自然につながります。',poster:'旅のポスター',posterTitle:'思い出をポスターに',posterCopy:'地図、ルート、写真を旅の記念に。',stats:'旅の統計',cities:'都市',statsTitle:'歩んだ距離が見える',statsCopy:'一年の探索を分かりやすいデータで振り返ります。',locationTools:'位置情報ツール',dragMap:'地図を動かして場所を探す',locationTitle:'写真に座標を戻す',locationCopy:'位置を追加・修正し、すべての写真を正しい場所へ。',photoFilter:'写真フィルター',springShort:'春',weekend:'週末',filterTitle:'何千枚から、この瞬間を',filterCopy:'時間、季節、場所ですばやく絞り込み。',browse:'横にスクロール',premium:'PhotoLoci プレミアム',premiumTitle:'一度の購入で、\nすべての機能を。',premiumButton:'アプリでプレミアムを見る',advanced:'プレミアムツール',lifetime:'一度の購入 · ずっと使える',yours:'写真はあなたのもの',privateTitle:'思い出はプライベート。\n処理も同じです。',onDevice:'デバイス上で処理',permissions:'アクセスは自分で管理',readPrivacy:'プライバシーポリシーを読む',next:'次の旅は写真から',rediscover:'訪れた場所を、\nもう一度。',finalCopy:'すべての写真に、地図上の居場所を。',footerCopy:'写真を、あの日の場所へ。',contact:'お問い合わせ',language:'言語'},
    ko:{map:'지도',journeys:'여정',privacy:'개인정보',download:'다운로드',designed:'iPhone 및 iPad용으로 설계',hero1:'사진을 그 순간의',hero2:'장소로 돌려놓으세요',lede:'지도에서 사진의 발자취를 탐색하고 여정을 다시 만나며, 다녀온 장소를 나만의 여행 이야기로 만들어 보세요.',explore:'기능 살펴보기',local:'계정 불필요 · 사진은 기기에 보관',photos:'사진 224장',spring:'어느 봄날',trail:'발자취 따라가기',geography:'나의 사진 지리',mapTitle:'사진 보관함은 나만의\n여행 지도이기도 합니다.',mapCopy:'도시의 한 모퉁이부터 수년간의 발자취까지. 확대하고 검색하고 시간순으로 둘러보며 사진을 다시 만나세요.',photoMap:'사진 지도 · 암스테르담',memories:'추억 224개',placeSearch:'장소 검색',placeSearchCopy:'기억 속 거리로 돌아가기',timeFilter:'시간 필터',timeFilterCopy:'연도, 월, 계절별 탐색',mapStyle:'지도 스타일',mapStyleCopy:'표준, 위성, 히트맵',toStories:'발자취에서 이야기로',beyond:'지도 그 이상.',storiesCopy:'흩어진 사진을 다시 보고 이해하고 공유할 수 있는 여정으로 정리하세요.',journey:'여정',journeyTitle:'하나의 경로를 한 장의 카드에',journeyCopy:'날짜, 장소, 사진이 자연스럽게 이어집니다.',poster:'여행 포스터',posterTitle:'추억을 포스터로',posterCopy:'지도, 경로, 사진이 여행 기념품이 됩니다.',stats:'여행 통계',cities:'도시',statsTitle:'얼마나 멀리 다녀왔는지 확인',statsCopy:'명확한 데이터로 한 해의 탐험을 돌아보세요.',locationTools:'위치 도구',dragMap:'지도를 움직여 장소 찾기',locationTitle:'사진 좌표 복원',locationCopy:'위치를 추가하거나 수정해 모든 사진을 제자리로.',photoFilter:'사진 필터',springShort:'봄',weekend:'주말',filterTitle:'수천 장 속 이 순간 찾기',filterCopy:'시간, 계절, 장소로 빠르게 좁혀보세요.',browse:'가로로 둘러보기',premium:'PhotoLoci 프리미엄',premiumTitle:'한 번 잠금 해제하고\n모든 도구를 사용하세요.',premiumButton:'앱에서 프리미엄 보기',advanced:'프리미엄 도구',lifetime:'한 번 구매 · 평생 사용',yours:'사진은 당신의 것',privateTitle:'추억은 사적인 것.\n처리도 그래야 합니다.',onDevice:'기기에서 처리',permissions:'접근 권한 직접 관리',readPrivacy:'개인정보 처리방침 읽기',next:'다음 여정은 사진에서 시작',rediscover:'다녀온 장소를\n다시 발견하세요.',finalCopy:'모든 사진이 지도 위 제자리를 찾도록.',footerCopy:'사진을 그 순간의 장소로.',contact:'문의',language:'언어'},
    nl:{map:'Kaart',journeys:'Reizen',privacy:'Privacy',download:'Download',designed:'Ontworpen voor iPhone en iPad',hero1:'Breng je foto’s terug',hero2:'naar waar ze zijn gemaakt',lede:'Verken je fotosporen op de kaart, herbeleef iedere reis en maak van bezochte plekken je eigen reisverhalen.',explore:'Ontdek de functies',local:'Geen account nodig · Foto’s blijven op je apparaat',photos:'224 foto’s',spring:'Een lente',trail:'Volg het spoor',geography:'Jouw fotogeografie',mapTitle:'Je fotobibliotheek is een reiskaart\ndie alleen van jou is.',mapCopy:'Van een straathoek tot jaren reizen. Zoom, zoek en blader door de tijd om je foto’s opnieuw te ontmoeten.',photoMap:'Fotokaart · Amsterdam',memories:'224 herinneringen',placeSearch:'Plaatsen zoeken',placeSearchCopy:'Terug naar die bekende straat',timeFilter:'Tijdfilters',timeFilterCopy:'Bekijk per jaar, maand of seizoen',mapStyle:'Kaartstijlen',mapStyleCopy:'Standaard, satelliet en heatmap',toStories:'Van sporen naar verhalen',beyond:'Meer dan een kaart.',storiesCopy:'Maak van losse foto’s reizen die je opnieuw kunt beleven, begrijpen en delen.',journey:'Reis',journeyTitle:'Bewaar een route op één kaart',journeyCopy:'Datums, plaatsen en foto’s vormen vanzelf een reis.',poster:'Reisposter',posterTitle:'Maak van een herinnering een poster',posterCopy:'Kaarten, routes en foto’s worden een reisherinnering.',stats:'Reisstatistieken',cities:'steden',statsTitle:'Zie hoe ver je bent gekomen',statsCopy:'Kijk met heldere gegevens terug op een jaar ontdekken.',locationTools:'Locatiehulpmiddelen',dragMap:'Sleep de kaart om de plek terug te vinden',locationTitle:'Herstel coördinaten van foto’s',locationCopy:'Voeg locaties toe of herstel ze, zodat elke foto zijn plek vindt.',photoFilter:'Fotofilters',springShort:'Lente',weekend:'Weekend',filterTitle:'Vind dit moment tussen duizenden',filterCopy:'Filter snel op tijd, seizoen en plaats.',browse:'Horizontaal bladeren',premium:'PhotoLoci Premium',premiumTitle:'Eén keer ontgrendelen.\nAlle premiumfuncties.',premiumButton:'Bekijk Premium in de app',advanced:'Premiumfuncties',lifetime:'Eenmalig · Voor altijd',yours:'Je foto’s zijn van jou',privateTitle:'Herinneringen zijn privé.\nDe verwerking dus ook.',onDevice:'Verwerkt op je apparaat',permissions:'Jij bepaalt de toegang',readPrivacy:'Lees het privacybeleid',next:'Je volgende halte begint in Foto’s',rediscover:'Herontdek de plekken\nwaar je bent geweest.',finalCopy:'Laat elke foto zijn plek op de kaart vinden.',footerCopy:'Breng foto’s terug naar waar ze zijn gemaakt.',contact:'Contact',language:'Taal'},
    'zh-TW':{map:'地圖',journeys:'旅程',privacy:'隱私',download:'下載',designed:'為 iPhone 與 iPad 設計',hero1:'把照片放回',hero2:'它們發生的地方',lede:'在地圖上探索照片足跡，重拾每一段旅程，並把走過的地方變成屬於你的旅行故事。',explore:'看看它能做什麼',local:'無需建立帳戶 · 照片留在你的裝置上',photos:'224 張照片',spring:'一個春天',trail:'沿著足跡繼續',geography:'你的照片地理',mapTitle:'相簿，也是一張\n只屬於你的旅行地圖。',mapCopy:'從城市裡的一個街角，到跨越數年的足跡。縮放、搜尋、按時間瀏覽，在熟悉的地圖上重新遇見那些照片。',photoMap:'照片地圖 · Amsterdam',memories:'224 個回憶',placeSearch:'地點搜尋',placeSearchCopy:'回到記憶中的街道',timeFilter:'時間篩選',timeFilterCopy:'按年月與季節瀏覽',mapStyle:'地圖樣式',mapStyleCopy:'標準、衛星與熱力圖',toStories:'從足跡，到故事',beyond:'不只是地圖。',storiesCopy:'把分散的照片，整理成可以重溫、理解，也可以分享的旅程。',journey:'旅程',journeyTitle:'把一段路，收進一張卡片',journeyCopy:'日期、地點與照片自然串成旅程。',poster:'旅行海報',posterTitle:'讓回憶成為一張海報',posterCopy:'地圖、路線和照片排成你的旅行紀念。',stats:'旅行統計',cities:'城市',statsTitle:'看見走過的距離',statsCopy:'用清晰的資料回望一年的探索。',locationTools:'位置工具',dragMap:'拖動地圖，找回地點',locationTitle:'為照片補回座標',locationCopy:'新增或修復位置，讓每張照片都能歸位。',photoFilter:'照片篩選',springShort:'春天',weekend:'週末',filterTitle:'從千張照片裡找到這一刻',filterCopy:'按時間、季節和地點快速縮小範圍。',browse:'橫向瀏覽',premium:'PhotoLoci 進階功能',premiumTitle:'一次解鎖，\n所有進階工具。',premiumButton:'在 App 內查看進階功能',advanced:'進階工具',lifetime:'一次解鎖 · 終身使用',yours:'照片屬於你',privateTitle:'回憶很私人。\n處理也應如此。',onDevice:'在裝置上處理',permissions:'由你決定權限',readPrivacy:'閱讀隱私政策',next:'下一站，從相簿開始',rediscover:'重新發現\n走過的地方。',finalCopy:'讓每一張照片，都在地圖上找到自己的位置。',footerCopy:'把照片放回它們發生的地方。',contact:'聯絡我們',language:'語言'}
  };
  const supplements = {
    de:{premiumCopy:'Reisen, Reiseposter, Statistiken sowie das Hinzufügen und Reparieren von Orten – plus Fotofilter und Ortssuche. Kein Abo.',regionalPrice:'Der Preis wird im App Store für deine Region angezeigt',onDeviceCopy:'Fotoanalyse und Kartenaggregation erfolgen auf deinem Gerät.',permissionsCopy:'Foto- und Standortzugriff lassen sich jederzeit in den Systemeinstellungen ändern.'},
    es:{premiumCopy:'Viajes, pósteres, estadísticas y herramientas para añadir o reparar ubicaciones, además de filtros y búsqueda. Sin suscripción.',regionalPrice:'El precio se muestra en el App Store según tu región',onDeviceCopy:'El análisis de fotos y la creación del mapa ocurren en tu dispositivo.',permissionsCopy:'Cambia el acceso a fotos y ubicación cuando quieras en Ajustes.'},
    fr:{premiumCopy:'Voyages, affiches, statistiques et outils pour ajouter ou corriger les lieux, avec filtres photo et recherche. Sans abonnement.',regionalPrice:'Le prix est affiché dans l’App Store selon votre région',onDeviceCopy:'L’analyse des photos et l’agrégation de la carte ont lieu sur votre appareil.',permissionsCopy:'Modifiez à tout moment l’accès aux photos et à la localisation dans les réglages.'},
    ja:{premiumCopy:'旅、ポスター、統計、位置の追加・修正、写真フィルター、場所検索。サブスクリプションはありません。',regionalPrice:'価格は地域に応じてApp Storeに表示されます',onDeviceCopy:'写真の分析と地図の集約はデバイス上で行われます。',permissionsCopy:'写真と位置情報へのアクセスは設定からいつでも変更できます。'},
    ko:{premiumCopy:'여정, 여행 포스터, 통계, 위치 추가 및 복구, 사진 필터와 장소 검색까지. 구독은 없습니다.',regionalPrice:'가격은 지역에 따라 App Store에 표시됩니다',onDeviceCopy:'사진 분석과 지도 집계는 기기에서 처리됩니다.',permissionsCopy:'사진과 위치 접근 권한은 시스템 설정에서 언제든 변경할 수 있습니다.'},
    nl:{premiumCopy:'Reizen, posters, statistieken en tools om locaties toe te voegen of te herstellen, plus fotofilters en zoeken. Geen abonnement.',regionalPrice:'De prijs wordt voor jouw regio in de App Store getoond',onDeviceCopy:'Fotoanalyse en kaartverwerking gebeuren op je apparaat.',permissionsCopy:'Wijzig foto- en locatietoegang op elk moment in de systeeminstellingen.'},
    'zh-TW':{premiumCopy:'旅程、旅行海報、統計、新增位置與位置修復；另含照片篩選和地點搜尋。沒有訂閱，也沒有倒數計時。',regionalPrice:'價格會在 App Store 中依你所在的地區顯示',onDeviceCopy:'照片分析與地圖彙整在你的裝置上完成。',permissionsCopy:'照片與位置存取權限可隨時在系統設定中更改。'}
  };
  Object.entries(supplements).forEach(([locale, extra]) => Object.assign(messages[locale], extra));
  const privacyPolicies = { de:'Datenschutzrichtlinie', en:'Privacy Policy', es:'Política de privacidad', fr:'Politique de confidentialité', ja:'プライバシーポリシー', ko:'개인정보 처리방침', nl:'Privacybeleid', 'zh-TW':'隱私政策' };
  Object.entries(privacyPolicies).forEach(([locale, value]) => { messages[locale].privacyPolicy = value; });

  const sourceToKey = Object.fromEntries(Object.entries(source).map(([key, value]) => [value.replace(/\n/g, ''), key]));
  const normalize = lang => {
    const lower = String(lang || '').toLowerCase();
    if (lower.startsWith('zh')) return /tw|hk|hant/.test(lower) ? 'zh-TW' : 'zh-CN';
    const short = lower.split('-')[0];
    return locales.includes(short) ? short : 'en';
  };
  const initial = normalize(localStorage.getItem('photoloci-language') || navigator.language);
  const originalText = new WeakMap();
  const translate = locale => {
    const dictionary = messages[locale] || messages.en;
    document.documentElement.lang = locale;
    document.documentElement.dataset.locale = locale;
    document.title = `PhotoLoci — ${locale === 'zh-CN' ? source.hero2 : dictionary.hero2}`;
    const description = document.querySelector('meta[name="description"]');
    if (description) description.content = locale === 'zh-CN' ? source.lede : dictionary.lede;
    document.querySelectorAll('body *:not(script):not(style):not(option)').forEach(element => {
      element.childNodes.forEach(node => {
        if (node.nodeType !== Node.TEXT_NODE || !node.textContent.trim()) return;
        if (!originalText.has(node)) originalText.set(node, node.textContent);
        const original = originalText.get(node);
        const clean = original.trim();
        const key = sourceToKey[clean];
        if (!key) return;
        const value = locale === 'zh-CN' ? source[key] : (dictionary[key] || messages.en[key] || source[key]);
        const translated = value.replace(/\n/g, '');
        node.textContent = original.replace(clean, translated);
      });
    });
    document.querySelectorAll('[data-i18n-lines]').forEach(element => {
      const key = element.dataset.i18nLines;
      const value = locale === 'zh-CN' ? source[key] : (dictionary[key] || messages.en[key] || source[key]);
      element.innerHTML = value.split('\n').map(part => `<span>${part}</span>`).join('<br>');
    });
    const picker = document.querySelector('.language-picker');
    if (picker) {
      const trigger = picker.querySelector('.language-trigger');
      trigger.querySelector('.language-current').textContent = labels[locale];
      trigger.setAttribute('aria-label', dictionary.language || messages.en.language);
      picker.querySelectorAll('.language-option').forEach(option => {
        const selected = option.dataset.locale === locale;
        option.setAttribute('aria-selected', selected);
        option.classList.toggle('selected', selected);
      });
    }
    localStorage.setItem('photoloci-language', locale);
  };

  const mountSelector = () => {
    const wrap = document.createElement('div');
    wrap.className = 'language-picker';
    wrap.innerHTML = `<button class="language-trigger" type="button" aria-haspopup="listbox" aria-expanded="false"><svg class="language-icon" aria-hidden="true" viewBox="0 0 20 20"><circle cx="10" cy="10" r="7.25"/><path d="M2.9 10h14.2M10 2.75c2.05 2 3.1 4.42 3.1 7.25S12.05 15.25 10 17.25C7.95 15.25 6.9 12.83 6.9 10S7.95 4.75 10 2.75Z"/></svg><span class="language-current"></span></button><div class="language-menu" role="listbox"></div>`;
    const trigger = wrap.querySelector('.language-trigger');
    const menu = wrap.querySelector('.language-menu');
    locales.forEach(locale => {
      const option = document.createElement('button');
      option.className = 'language-option';
      option.type = 'button';
      option.role = 'option';
      option.dataset.locale = locale;
      option.innerHTML = `<span>${labels[locale]}</span><i aria-hidden="true">✓</i>`;
      option.addEventListener('click', () => { translate(locale); close(); trigger.focus(); });
      menu.append(option);
    });
    const open = () => { wrap.classList.add('open'); trigger.setAttribute('aria-expanded', 'true'); menu.querySelector('.selected')?.focus(); };
    const close = () => { wrap.classList.remove('open'); trigger.setAttribute('aria-expanded', 'false'); };
    trigger.addEventListener('click', () => wrap.classList.contains('open') ? close() : open());
    trigger.addEventListener('keydown', event => { if (['ArrowDown','ArrowUp','Enter',' '].includes(event.key)) { event.preventDefault(); open(); } });
    menu.addEventListener('keydown', event => {
      const options = [...menu.querySelectorAll('.language-option')];
      const index = options.indexOf(document.activeElement);
      if (event.key === 'Escape') { close(); trigger.focus(); }
      else if (event.key === 'ArrowDown') { event.preventDefault(); options[(index + 1) % options.length].focus(); }
      else if (event.key === 'ArrowUp') { event.preventDefault(); options[(index - 1 + options.length) % options.length].focus(); }
      else if (event.key === 'Home') { event.preventDefault(); options[0].focus(); }
      else if (event.key === 'End') { event.preventDefault(); options.at(-1).focus(); }
    });
    document.addEventListener('pointerdown', event => { if (!wrap.contains(event.target)) close(); });
    const nav = document.querySelector('.site-nav');
    if (nav) nav.insertBefore(wrap, nav.querySelector('.nav-download'));
    else { wrap.classList.add('language-picker-standalone'); document.body.prepend(wrap); }
  };

  mountSelector();
  translate(initial);
})();
